spring:
  h2:
    console:
      enabled: true
  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:28e66dd1-75ef-4730-b788-16784f15c5a2
#    username: sa
#    password:
    url: jdbc:mysql://localhost:3306/fast?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password:
    initialization-mode: always #import.sql을 사용할 때 배포시에는 none이 되어야 함
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: create-drop
#      ddl-auto: update


